spring:
  cache:
      type: redis
  redis:
    host: 192.168.200.130
    port: 6379
    jedis: # 设置redis连接池
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
        max-active: 10